name: CI

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs
  semrel:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: byteshard/templates/semrel@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}